<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Asen-PC" name="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test" tests="14" failures="0" timestamp="31 Dec 2015 08:09:51 GMT" time="31.180" errors="1">
  <testcase name="add" time="3.980" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="delete" time="0.377" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="delete" time="0.438" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="add" time="2.673" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="query" time="2.006" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="query" time="1.695" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="delete" time="0.451" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="query" time="2.079" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="add" time="3.806" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="delete" time="0.481" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="add" time="3.885" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="add" time="3.683" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="add" time="4.165" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="query" time="1.461" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test.query(Drilltraining_Drillscenemanager_test.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- query -->
</testsuite> <!-- com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test -->
