<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Asen-PC" name="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test" tests="14" failures="0" timestamp="9 Jan 2016 04:53:42 GMT" time="80.057" errors="1">
  <testcase name="add" time="50.597" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="add" time="5.922" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="query" time="1.561" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="query" time="1.506" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test.query(Drilltraining_Drillscenemanager_test.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
]]>
    </error>
  </testcase> <!-- query -->
  <testcase name="query" time="3.855" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="add" time="2.317" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="add" time="3.693" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="delete" time="0.408" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="delete" time="0.348" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="add" time="3.697" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="delete" time="0.400" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="add" time="3.704" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="query" time="1.713" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
  <testcase name="delete" time="0.336" classname="com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test"/>
</testsuite> <!-- com.auto.cases.drilltraining.Drilltraining_Drillscenemanager_test -->
